# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PrintShift
email: paenian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The PrintShift Project is enabling part ejection for 3D Printers, starting with the Prusa Mini.  Turn your 3D Printer into a 3D factory!
twitter_username: paenian
github_username: paenian
minimal_mistakes_skin: default
search: true
repository: paenian/PrintShift

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    
collections:
  portfolio:
    output: true

author:
  name   : "Paul Chase"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Maker of kinetic sculptures, including 3D printers"
  links:
    - label: "Patreon"
      icon: "fab fa-fw fa-patreon"
      url: "https://www.patreon.com/PrintShift"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/paenian"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paenian"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/paenian"

footer:
  links:
    - label: "Patreon"
      icon: "fab fa-fw fa-patreon"
      url: "https://www.patreon.com/PrintShift"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/paenian"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paenian"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/paenian"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      comments: true
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
